"""Agent implementations for the multi-agent RAG flow.

This module defines four LangChain agents (Planning, Retrieval, Summarization,
Verification) and thin node functions that LangGraph uses to invoke them.
"""

from typing import List

from langchain.agents import create_agent
from langchain_core.messages import AIMessage, HumanMessage, ToolMessage

from ..llm.factory import create_chat_model
from .prompts import (
    PLANNING_SYSTEM_PROMPT,
    RETRIEVAL_SYSTEM_PROMPT,
    SUMMARIZATION_SYSTEM_PROMPT,
    VERIFICATION_SYSTEM_PROMPT,
)
from .state import QAState
from .tools import retrieval_tool


def _extract_last_ai_content(messages: List[object]) -> str:
    """Extract the content of the last AIMessage in a messages list."""
    for msg in reversed(messages):
        if isinstance(msg, AIMessage):
            return str(msg.content)
    return ""


# Define agents at module level for reuse
planning_agent = create_agent(
    model=create_chat_model(),
    tools=[],
    system_prompt=PLANNING_SYSTEM_PROMPT,
)

retrieval_agent = create_agent(
    model=create_chat_model(),
    tools=[retrieval_tool],
    system_prompt=RETRIEVAL_SYSTEM_PROMPT,
)

summarization_agent = create_agent(
    model=create_chat_model(),
    tools=[],
    system_prompt=SUMMARIZATION_SYSTEM_PROMPT,
)

verification_agent = create_agent(
    model=create_chat_model(),
    tools=[],
    system_prompt=VERIFICATION_SYSTEM_PROMPT,
)


def planning_node(state: QAState) -> QAState:
    """Planning Agent node with professional entry and exit logging.
    Planning Agent node: decomposes the user question into a search strategy.

    This node:
    - Sends the raw user question to the Planning Agent.
    - The agent breaks the question into a natural language 'plan' and specific 'sub-questions'.
    - Parses the agent's response to extract these components.
    - Stores `plan` and `sub_questions` in the state for the Retrieval Agent to use.
    """
    question = state["question"]

    
    # NODE ENTRY LOG: Makes the planning step visible in console
    print(f"\n[AGENT: PLANNING] ===== NODE START =====")
    print(f"[AGENT: PLANNING] Received Question: {question}")

    result = planning_agent.invoke({"messages": [HumanMessage(content=question)]})
    content = _extract_last_ai_content(result.get("messages", []))
    
    try:
        plan_part = content.split("Sub-questions:")[0].replace("Plan:", "").strip()
        sub_q_part = content.split("Sub-questions:")[-1].strip()
        sub_questions = [q.strip("- ").strip() for q in sub_q_part.split("\n") if q.strip()]
        # NODE EXIT LOG: Displays the strategy and decomposition
        print(f"[AGENT: PLANNING] Plan Strategy: {plan_part}")
        print(f"[AGENT: PLANNING] Generated Sub-questions: {sub_questions}")
        print(f"[AGENT: PLANNING] ===== NODE COMPLETE =====\n")

    except Exception as e:
        print(f"[AGENT: PLANNING] !! Parsing Error: {e}. Falling back to default.")
        plan_part = "Direct retrieval strategy"
        sub_questions = [question]

    return {
        "plan": plan_part,
        "sub_questions": sub_questions
    }


def retrieval_node(state: QAState) -> QAState:
    """Retrieval Agent node: gathers context using the decomposed search plan.

    This node:
    - Iterates through the list of `sub_questions` generated by the Planning Agent.
    - For each sub-question, invokes the Retrieval Agent to fetch relevant chunks.
    - Aggregates all retrieved context into a single, organized string.
    - Stores the consolidated context in `state["context"]`.
    """
    print(f"\n[AGENT: RETRIEVAL] ===== NODE START =====")

    # Use sub_questions from the plan, or fall back to the original question
    queries = state.get("sub_questions") or [state["question"]]
    all_contexts = []

    for idx, query in enumerate(queries, start=1):
        print(f"[AGENT: RETRIEVAL] Running query {idx}/{len(queries)}: {query}")

        result = retrieval_agent.invoke({"messages": [HumanMessage(content=query)]})
        messages = result.get("messages", [])
        
        for msg in reversed(messages):
            if isinstance(msg, ToolMessage):
                all_contexts.append(f"--- Context for: {query} ---\n{msg.content}")
                break
    
    print(f"[AGENT: RETRIEVAL] Successfully aggregated {len(all_contexts)} context blocks.")
    print(f"[AGENT: RETRIEVAL] ===== NODE COMPLETE =====\n")

    return {
        "context": "\n\n".join(all_contexts),
    }


def summarization_node(state: QAState) -> QAState:
    """Summarization Agent node: generates draft answer from context.

    This node:
    - Sends question + context to the Summarization Agent.
    - Agent responds with a draft answer grounded only in the context.
    - Stores the draft answer in `state["draft_answer"]`.
    """
    question = state["question"]
    context = state.get("context")

    user_content = f"Question: {question}\n\nContext:\n{context}"

    result = summarization_agent.invoke(
        {"messages": [HumanMessage(content=user_content)]}
    )
    messages = result.get("messages", [])
    draft_answer = _extract_last_ai_content(messages)

    return {
        "draft_answer": draft_answer,
    }


def verification_node(state: QAState) -> QAState:
    """Verification Agent node: verifies and corrects the draft answer.

    This node:
    - Sends question + context + draft_answer to the Verification Agent.
    - Agent checks for hallucinations and unsupported claims.
    - Stores the final verified answer in `state["answer"]`.
    """
    question = state["question"]
    context = state.get("context", "")
    draft_answer = state.get("draft_answer", "")

    user_content = f"""Question: {question}

Context:
{context}

Draft Answer:
{draft_answer}

Please verify and correct the draft answer, removing any unsupported claims."""

    result = verification_agent.invoke(
        {"messages": [HumanMessage(content=user_content)]}
    )
    messages = result.get("messages", [])
    answer = _extract_last_ai_content(messages)

    return {
        "answer": answer,
    }
